# Generated by Django 3.2.8 on 2021-10-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0002_auto_20211007_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='foto_aluno',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/'),
        ),
    ]
