# Generated by Django 3.2.8 on 2021-10-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0003_aluno_foto_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='foto_aluno',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
