# Generated by Django 3.2.8 on 2021-10-11 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0004_alter_aluno_foto_aluno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='cpf',
        ),
    ]
