# Generated by Django 3.2.8 on 2021-10-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0005_remove_aluno_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='data_expedicao',
            field=models.DateField(default='2020-01-01', verbose_name='Data de expedição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='numero_rg',
            field=models.CharField(default='123', max_length=30, verbose_name='Número do RG'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='uf_emissao_rg',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas')], default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(default='2020-01-01', verbose_name='Data de Nascimento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='foto_aluno',
            field=models.ImageField(upload_to='fotos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], default='', max_length=30),
            preserve_default=False,
        ),
    ]
