# Generated by Django 3.2.8 on 2021-10-07 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField()),
                ('nome_aluno', models.CharField(max_length=200)),
                ('curso', models.CharField(max_length=100)),
                ('observacao', models.TextField()),
                ('data_matricula', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Matricula de Aluno',
                'verbose_name_plural': 'Matriculas de Alunos',
                'ordering': ['nome_aluno'],
            },
        ),
    ]
