# Generated by Django 3.2.8 on 2021-10-07 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_auto_20211007_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='ch_total',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Carga Horária Total do Curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='codigo',
            field=models.CharField(help_text='Código usado para composição de turmas e matrículas', max_length=10, unique=True, verbose_name='Código do Curso'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edu_curso', to='edu.curso', verbose_name='Curso'),
        ),
    ]
